branches:
  only:
    - master

language: python

python:
  - 2.6
  - 2.7

env:
  - REQUIREMENTS=1.3.X            TESTS="mutant boolean temporal file numeric related text web south"     SETTINGS=test_project.settings
  - REQUIREMENTS=1.3.X-postgres   TESTS="mutant boolean temporal file numeric related text web south"     SETTINGS=travis.postgres_settings TEMPLATE=template0
  - REQUIREMENTS=1.3.X-postgres   TESTS="mutant boolean temporal file numeric related text web geo south" SETTINGS=travis.postgis_settings TEMPLATE=template_postgis
  - REQUIREMENTS=1.4.X            TESTS="mutant boolean temporal file numeric related text web south"     SETTINGS=test_project.settings
  - REQUIREMENTS=1.4.X-postgres   TESTS="mutant boolean temporal file numeric related text web south"     SETTINGS=travis.postgres_settings TEMPLATE=template0
  - REQUIREMENTS=1.4.X-postgres   TESTS="mutant boolean temporal file numeric related text web geo south" SETTINGS=travis.postgis_settings TEMPLATE=template_postgis
  - REQUIREMENTS=master           TESTS="mutant boolean temporal file numeric related text web south"     SETTINGS=test_project.settings
  - REQUIREMENTS=master-postgres  TESTS="mutant boolean temporal file numeric related text web south"     SETTINGS=travis.postgres_settings TEMPLATE=template0
  - REQUIREMENTS=master-postgres  TESTS="mutant boolean temporal file numeric related text web geo south" SETTINGS=travis.postgis_settings TEMPLATE=template_postgis
  - REQUIREMENTS=mongo            TESTS="mutant boolean temporal file numeric nonrel text web"            SETTINGS=mongodb_settings

postgres:
  adapter: postgresql
  database: mutant
  username: postgres

install:
  - pip install -r requirements/$REQUIREMENTS.txt --use-mirrors -I
  - python setup.py install

before_script:
  - "if [ -d '/usr/share/postgresql/8.4/' ]; then PG='8.4'; else PG='9.1'; fi"
  - "if echo $SETTINGS | grep 'postgis'; then sudo apt-get update && sudo apt-get install binutils gdal-bin libproj-dev postgresql-${PG}-postgis; fi"
  - "if echo $SETTINGS | grep 'postgis'; then sudo su postgres -c './tests/travis/create_template_postgis-debian.sh'; fi"
  - "if echo $SETTINGS | grep -E '(postgres|postgis)'; then psql -c \"CREATE DATABASE mutant TEMPLATE ${TEMPLATE};\" -U postgres; fi"

script:
  - cd tests
  - python manage.py test $TESTS --settings=$SETTINGS
