language: python
python:
  - 2.5
  - 2.6
  - 2.7
install:
  - pip install -r requirements
  - pip install psycopg2==2.4.1
  - python setup.py install
postgres:
  adapter: postgresql
  database: mutant
  username: postgres
script:
  - cd tests
  - python manage.py test mutant
  - python manage.py test mutant --settings=travis_postgres_settings