language: python
python:
  - 2.6
  - 2.7
install:
  - pip install -r requirements
  - pip install psycopg2==2.4.1
  - python setup.py install
postgres:
  adapter: postgresql
  database: mutant
  username: postgres
script:
  - cd tests
  - echo "Testing sqlite with stable django"
  - python manage.py test mutant
  - echo ""
  - echo "Testing postgres with stable django"
  - python manage.py test mutant --setings=travis_postgres_settings
  - echo ""