language: python
python:
  - 2.6
  - 2.7
env:
  - REQUIREMENTS=stable TESTS="test mutant boolean datetime file numeric related text web" SETTINGS=test_project.settings
  - REQUIREMENTS=stable-postgres TESTS="test mutant boolean datetime file numeric related text web" SETTINGS=travis.postgres_settings
  - REQUIREMENTS=trunk TESTS="test mutant boolean datetime file numeric related text web" SETTINGS=test_project.settings
  - REQUIREMENTS=trunk-postgres TESTS="test mutant boolean datetime file numeric related text web" SETTINGS=travis.postgres_settings
  - REQUIREMENTS=mongo TESTS="test mutant boolean datetime file numeric nonrel text web" SETTINGS=mongodb_settings
install:
  - pip install -r requirements/$REQUIREMENTS.txt
  - python setup.py install
postgres:
  adapter: postgresql
  database: mutant
  username: postgres
before_script:
  - "psql -c 'create database mutant;' -U postgres"
script:
  - cd tests
  - python manage.py test $TESTS --settings=$SETTINGS
