language: python
python:
  - 2.6
  - 2.7
install:
  - pip install -r requirements
  - pip install psycopg2==2.4.1
  - python setup.py install
postgres:
  adapter: postgresql
  database: mutant
  username: postgres
before_script:
  - "psql -c 'create database mutant;' -U postgres"
script:
  - cd tests
  - python manage.py test mutant
  - python manage.py test mutant --settings=travis_postgres_settings
  - pip uninstall django && pip install -e git+https://github.com/django/django#egg=django
  - python manage.py test mutant
  - python manage.py test mutant --settings=travis_postgres_settings