language: python
python:
  - 2.6
  - 2.7
install:
  - pip install -r requirements
  - pip install psycopg2==2.4.1
  - python setup.py install
postgres:
  adapter: postgresql
  database: mutant
  username: postgres
before_script:
  - "psql -c 'create database mutant;' -U postgres"
script:
  - cd tests
  - python manage.py test mutant boolean datetime file numeric related text web
  - python manage.py test mutant boolean datetime file numeric related text web --settings=travis.postgres_settings
  - pip uninstall django -y && pip install https://github.com/django/django/tarball/master
  - python manage.py test mutant boolean datetime file numeric related text web
  - python manage.py test mutant boolean datetime file numeric related text web --settings=travis.postgres_settings
  - pip install https://github.com/django-nonrel/django-nonrel/tarball/develop -I
  - pip install https://github.com/django-nonrel/djangotoolbox/tarball/develop
  - pip install https://github.com/charettes/mongodb-engine/tarball/fix-south-adapter
  - python manage.py test mutant boolean datetime file numeric nonrel text web --settings=mongodb_settings