branches:
  only:
    - master

language: python

python:
  - 2.6
  - 2.7

env:
  - REQUIREMENTS=1.4.X SETTINGS=sqlite3
  - REQUIREMENTS=1.4.X-postgres SETTINGS=postgresql_psycopg2 TEMPLATE=template0
  - REQUIREMENTS=1.4.X-postgres SETTINGS=postgis TEMPLATE=template_postgis
  - REQUIREMENTS=1.5.X SETTINGS=sqlite3
  - REQUIREMENTS=1.5.X-postgres SETTINGS=postgresql_psycopg2 TEMPLATE=template0
  - REQUIREMENTS=1.5.X-postgres SETTINGS=postgis TEMPLATE=template_postgis
  - REQUIREMENTS=master SETTINGS=sqlite3
  - REQUIREMENTS=master-postgres SETTINGS=postgresql_psycopg2 TEMPLATE=template0
  - REQUIREMENTS=master-postgres SETTINGS=postgis TEMPLATE=template_postgis

matrix:
  allow_failures:
    - env: REQUIREMENTS=master SETTINGS=sqlite3
    - env: REQUIREMENTS=master-postgres SETTINGS=postgresql_psycopg2 TEMPLATE=template0
    - env: REQUIREMENTS=master-postgres SETTINGS=postgis TEMPLATE=template_postgis

install:
  - pip install argparse coverage django-coverage -q --use-mirrors
  - pip install -r requirements/$REQUIREMENTS.txt -q --use-mirrors

before_script:
  - if echo $SETTINGS | grep 'postgis' -q; then sudo apt-get install binutils gdal-bin libproj-dev postgresql-9.1-postgis -q > /dev/null; fi
  - if echo $SETTINGS | grep 'postgis' -q; then sudo su postgres -c './create_template_postgis-debian.sh' > /dev/null; fi
  - if echo $SETTINGS | grep -E '(postgresql|postgis)' -q; then psql -c "CREATE DATABASE mutant TEMPLATE ${TEMPLATE};" -U postgres -q; fi

script:
  - python -Wonce `which django-admin.py` test_coverage --pythonpath=`pwd` --settings=tests.settings.$SETTINGS -v2
