language: python
python:
  - 2.6
  - 2.7
env:
  - REQUIREMENTS=stable TESTS="mutant boolean datetime file numeric related text web" SETTINGS=test_project.settings
  - REQUIREMENTS=stable-postgres TESTS="mutant boolean datetime file numeric related text web" SETTINGS=travis.postgres_settings
  - REQUIREMENTS=trunk TESTS="mutant boolean datetime file numeric related text web" SETTINGS=test_project.settings
  - REQUIREMENTS=trunk-postgres TESTS="mutant boolean datetime file numeric related text web" SETTINGS=travis.postgres_settings
  - REQUIREMENTS=mongo TESTS="mutant boolean datetime file numeric nonrel text web" SETTINGS=mongodb_settings
postgres:
  adapter: postgresql
  database: mutant
  username: postgres
install:
  - python setup.py install
  - pip install -r requirements/$REQUIREMENTS.txt --use-mirrors -I
before_script:
  - "psql -c 'create database mutant;' -U postgres"
script:
  - cd tests
  - python manage.py test $TESTS --settings=$SETTINGS
