branches:
  only:
    - master

language: python

python:
  - 2.6
  - 2.7

env:
  - REQUIREMENTS=1.3.X           TESTS="mutant boolean temporal file numeric related text web polymodels"           ENGINE=sqlite3
  - REQUIREMENTS=1.3.X-postgres  TESTS="mutant boolean temporal file numeric related text web polymodels"           ENGINE=postgresql TEMPLATE=template0
  - REQUIREMENTS=1.3.X-postgres  TESTS="mutant boolean temporal file numeric related text web geo polymodels"       ENGINE=postgis    TEMPLATE=template_postgis
  - REQUIREMENTS=mongo           TESTS="mutant boolean temporal file numeric nonrel text web polymodels"            ENGINE=mongodb
  - REQUIREMENTS=1.4.X           TESTS="mutant boolean temporal file numeric related text web polymodels"           ENGINE=sqlite3
  - REQUIREMENTS=1.4.X-postgres  TESTS="mutant boolean temporal file numeric related text web polymodels"           ENGINE=postgresql TEMPLATE=template0
  - REQUIREMENTS=1.4.X-postgres  TESTS="mutant boolean temporal file numeric related text web geo polymodels"       ENGINE=postgis    TEMPLATE=template_postgis
  - REQUIREMENTS=master          TESTS="mutant boolean temporal file numeric related text web south polymodels"     ENGINE=sqlite3
  - REQUIREMENTS=master-postgres TESTS="mutant boolean temporal file numeric related text web south polymodels"     ENGINE=postgresql TEMPLATE=template0
  - REQUIREMENTS=master-postgres TESTS="mutant boolean temporal file numeric related text web geo south polymodels" ENGINE=postgis    TEMPLATE=template_postgis

matrix:
  allow_failures:
    - env: REQUIREMENTS=mongo           TESTS="mutant boolean temporal file numeric nonrel text web polymodels"            ENGINE=mongodb
    - env: REQUIREMENTS=master          TESTS="mutant boolean temporal file numeric related text web south polymodels"     ENGINE=sqlite3
    - env: REQUIREMENTS=master-postgres TESTS="mutant boolean temporal file numeric related text web south polymodels"     ENGINE=postgresql TEMPLATE=template0
    - env: REQUIREMENTS=master-postgres TESTS="mutant boolean temporal file numeric related text web geo south polymodels" ENGINE=postgis    TEMPLATE=template_postgis

postgres:
  adapter: postgresql
  database: mutant
  username: postgres

install:
  - pip install argparse --use-mirrors
  - pip install -r requirements/$REQUIREMENTS.txt --use-mirrors
  - python setup.py install

before_script:
  - "if [ -d '/usr/share/postgresql/8.4/' ]; then PG='8.4'; else PG='9.1'; fi"
  - "if echo $ENGINE | grep 'postgis'; then sudo apt-get install binutils gdal-bin libproj-dev postgresql-${PG}-postgis; fi"
  - "if echo $ENGINE | grep 'postgis'; then sudo su postgres -c './create_template_postgis-debian.sh'; fi"
  - "if echo $ENGINE | grep -E '(postgresql|postgis)'; then psql -c \"CREATE DATABASE mutant TEMPLATE ${TEMPLATE};\" -U postgres; fi"

script:
  - python runtests.py $TESTS --engine=$ENGINE
