sudo: no

language: python

addons:
  postgresql: "9.3"

services:
  - redis-server

env:
  - TOXENV=flake8
  - TOXENV=py26-1.6-sqlite
  - TOXENV=py26-1.6-postgresql
  - TOXENV=py26-1.6-postgis
  - TOXENV=py27-1.6-sqlite
  - TOXENV=py27-1.6-postgresql
  - TOXENV=py27-1.6-postgis
  - TOXENV=py27-master-sqlite
  - TOXENV=py27-master-postgresql
  - TOXENV=py27-master-postgis
  - TOXENV=py32-1.6-sqlite
  - TOXENV=py32-1.6-postgresql
  - TOXENV=py32-1.6-postgis
  - TOXENV=py33-1.6-sqlite
  - TOXENV=py33-1.6-postgresql
  - TOXENV=py33-1.6-postgis
  - TOXENV=py34-master-sqlite
  - TOXENV=py34-master-postgresql
  - TOXENV=py34-master-postgis

matrix:
  allow_failures:
    - env: TOXENV=py27-master-sqlite
    - env: TOXENV=py27-master-postgresql
    - env: TOXENV=py27-master-postgis
    - env: TOXENV=py34-master-sqlite
    - env: TOXENV=py34-master-postgresql
    - env: TOXENV=py34-master-postgis

install:
  - pip install tox coveralls

before_script:
  - if echo $TOXENV | grep -E '(-postgresql|-postgis)' -q; then psql -U postgres -c "CREATE DATABASE mutant;"; fi
  - if echo $TOXENV | grep '\-postgis' -q; then psql mutant -U postgres -c "CREATE EXTENSION postgis; CREATE EXTENSION postgis_topology;"; fi

script:
  - tox

after_success:
  - coveralls
