branches:
  only:
    - master

language: python

python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3

addons:
  postgresql: "9.3"

services:
  - redis-server

env:
  - REQUIREMENTS=1.6.X BACKEND=sqlite3
  - REQUIREMENTS=1.6.X-postgres BACKEND=postgresql_psycopg2
  - REQUIREMENTS=1.6.X-postgres BACKEND=postgis
  - REQUIREMENTS=1.7.X BACKEND=sqlite3
  - REQUIREMENTS=1.7.X-postgres BACKEND=postgresql_psycopg2
  - REQUIREMENTS=1.7.X-postgres BACKEND=postgis
  - REQUIREMENTS=master BACKEND=sqlite3
  - REQUIREMENTS=master-postgres BACKEND=postgresql_psycopg2
  - REQUIREMENTS=master-postgres BACKEND=postgis

matrix:
  exclude:
    - python: 2.6
      env: REQUIREMENTS=1.7.X BACKEND=sqlite3
    - python: 2.6
      env: REQUIREMENTS=1.7.X-postgres BACKEND=postgresql_psycopg2
    - python: 2.6
      env: REQUIREMENTS=1.7.X-postgres BACKEND=postgis
    - python: 2.6
      env: REQUIREMENTS=master BACKEND=sqlite3
    - python: 2.6
      env: REQUIREMENTS=master-postgres BACKEND=postgresql_psycopg2
    - python: 2.6
      env: REQUIREMENTS=master-postgres BACKEND=postgis
  allow_failures:
    - env: REQUIREMENTS=1.7.X BACKEND=sqlite3
    - env: REQUIREMENTS=1.7.X-postgres BACKEND=postgresql_psycopg2
    - env: REQUIREMENTS=1.7.X-postgres BACKEND=postgis
    - env: REQUIREMENTS=master BACKEND=sqlite3
    - env: REQUIREMENTS=master-postgres BACKEND=postgresql_psycopg2
    - env: REQUIREMENTS=master-postgres BACKEND=postgis

install:
  - pip install -r requirements/$REQUIREMENTS.txt coveralls redis
  - pip freeze

before_script:
  - if echo $BACKEND | grep 'postgis' -q; then sudo apt-get install postgis; fi
  - if echo $BACKEND | grep -E '(postgresql|postgis)' -q; then psql -U postgres -c "CREATE DATABASE mutant;"; fi
  - if echo $BACKEND | grep 'postgis' -q; then psql mutant -U postgres -c "CREATE EXTENSION postgis; CREATE EXTENSION postgis_topology;"; fi

script:
  - python -Wonce `which coverage` run `which django-admin.py` test --pythonpath=`pwd` --settings=mutant.tests.settings.$BACKEND -v2

after_success:
  - coverage report -m
  - coveralls
